force-app/main/default/objects/Custom_Widget__c/Custom_Widget__c.object-meta.xml
<CustomObject>
    <label>Custom Widget</label>
    <nameField>
        <displayFormat>CW-{00000}</displayFormat>
        <label>Custom Widget Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Widgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Widget__c/fields/Is_Properly_Nested__c.field-meta.xml
<CustomField>
    <fullName>Is_Properly_Nested__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Properly Nested</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/nestedParanthesisCheckBatchTest.cls
@IsTest
public class nestedParanthesisCheckBatchTest {
    @IsTest
    static void withInvalidPatternForBatchTest() {    
        Custom_Widget__c cwRec = CreateCustomWidgetTestDataFactory.getInValidCustomWidgetRecord(); 
        test.startTest();       
           database.executeBatch(new nestedParanthesisCheckBatch());        
        test.stopTest();
        Custom_Widget__c cwRec1 = [select id,Is_Properly_Nested__c from Custom_Widget__c where Id=:cwRec.Id];  
        system.assertEquals(false,cwRec1.Is_Properly_Nested__c);
    }
    @IsTest
    static void withValidPatternForBatchTest() {    
        Custom_Widget__c cwRec = CreateCustomWidgetTestDataFactory.getValidCustomWidgetRecord(); 
        test.startTest();       
           database.executeBatch(new nestedParanthesisCheckBatch());        
        test.stopTest();
        Custom_Widget__c cwRec1 = [select id,Is_Properly_Nested__c from Custom_Widget__c where Id=:cwRec.Id];  
        system.assertEquals(true,cwRec1.Is_Properly_Nested__c);       
    }
}