force-app/main/default/objects/Custom_Widget__c/Custom_Widget__c.object-meta.xml
<CustomObject>
    <label>Custom Widget</label>
    <nameField>
        <displayFormat>CW-{00000}</displayFormat>
        <label>Custom Widget Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Widgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Widget__c/fields/Is_Properly_Nested__c.field-meta.xml
<CustomField>
    <fullName>Is_Properly_Nested__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Properly Nested</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CreateWidgetController.cls
public with sharing class CreateWidgetController {
    @AuraEnabled
    public static void createWidget(String value,Boolean isNestedProperly){
        Custom_Widget__c widgtRec = new Custom_Widget__c();
        widgtRec.Value__c=value;
        widgtRec.Is_Properly_Nested__c=isNestedProperly;
        widgtRec.ownerId = UserInfo.getUserId();
        try {            
            insert widgtRec;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }    
}